image: gcc:latest

stages:
  - build


build-debug:
  stage: build
  before_script: 
    - apt update && apt -y install cmake
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make all #VERBOSE=1


# build-release:
#   stage: build
#   before_script: 
#     - apt update && apt -y install cmake
#   script:
#     - mkdir build
#     - cd build
#     - cmake .. -DCMAKE_BUILD_TYPE=Release
#     - make all #VERBOSE=1
